import type { Locale } from './i18n';
const copy={
 en:{email:'Email confirmation needed',received:'Your email confirmation request was accepted. Check your inbox and spam folder. If you already have a confirmed account, sign in instead; registering again may not send another email.',notSubmitted:'Your organisation request has not been submitted yet. After confirming your email, sign in, attach the mandate documents and submit it for manual review.',confirmed:'Your email is confirmed. Your organisation request has not been submitted yet.',pending:'Your request has been received and is awaiting an administrator’s review. Editing remains locked. You can check the status and any request for further information here.',progress:['Create your sign-in','Confirm email and attach mandate documents','Submit for manual review','Wait for an administrator’s decision'],working:'Sending your request…',resend:'Resend confirmation email',resendIntro:'No confirmation email? Enter the same address used for registration. If it is already confirmed, sign in.',resent:'The confirmation request was accepted. If the address is eligible, check your inbox and spam folder. Already confirmed accounts should sign in.',rate:'The email service is limiting requests. Wait before trying again. If you have already confirmed your account, sign in instead.',unauthorized:'Supabase’s temporary email service cannot send to this address. For this test phase, use an address authorised in the NERUMA project. Public email delivery will require our own SMTP service.',unconfirmed:'Confirm your email before signing in. You can request another confirmation below.',emailError:'The email request was not completed. No organisation request was submitted. Try again later or sign in if you already have a confirmed account.',loginError:'Sign-in failed. Check the email and password, and confirm your email first.',requestError:'Your organisation request was not submitted. Check the document uploads and reload if the request changed.',stale:'Your organisation request changed. Reload the page before submitting again.'},
 ro:{email:'Este necesară confirmarea emailului',received:'Solicitarea de confirmare a emailului a fost acceptată. Verifică inboxul și folderul spam. Dacă ai deja un cont confirmat, autentifică-te; o nouă înregistrare poate să nu trimită alt email.',notSubmitted:'Cererea organizației nu a fost încă trimisă. După confirmarea emailului, autentifică-te, atașează documentele de mandat și trimite cererea pentru verificare manuală.',confirmed:'Emailul tău este confirmat. Cererea organizației nu a fost încă trimisă.',pending:'Cererea a fost primită și așteaptă verificarea unui administrator. Editarea rămâne blocată. Aici poți vedea starea și eventualele solicitări de completare.',progress:['Creează datele de autentificare','Confirmă emailul și atașează documentele','Trimite pentru verificare manuală','Așteaptă decizia administratorului'],working:'Trimitem solicitarea…',resend:'Retrimite emailul de confirmare',resendIntro:'Nu ai primit confirmarea? Introdu aceeași adresă folosită la înregistrare. Dacă este deja confirmată, autentifică-te.',resent:'Solicitarea de confirmare a fost acceptată. Dacă adresa este eligibilă, verifică inboxul și spamul. Pentru conturile deja confirmate, folosește autentificarea.',rate:'Serviciul de email limitează solicitările. Așteaptă înainte să încerci din nou. Dacă ai confirmat deja contul, autentifică-te.',unauthorized:'Serviciul temporar de email Supabase nu poate trimite la această adresă. În etapa de test, folosește o adresă autorizată în proiectul NERUMA. Trimiterea publică va necesita serviciul nostru SMTP.',unconfirmed:'Confirmă emailul înainte de autentificare. Poți solicita o nouă confirmare mai jos.',emailError:'Solicitarea emailului nu a fost finalizată. Cererea organizației nu a fost trimisă. Încearcă mai târziu sau autentifică-te dacă ai deja cont confirmat.',loginError:'Autentificarea a eșuat. Verifică emailul și parola și confirmă mai întâi adresa de email.',requestError:'Cererea organizației nu a fost trimisă. Verifică documentele încărcate și reîncarcă pagina dacă cererea a fost modificată.',stale:'Cererea organizației a fost modificată. Reîncarcă pagina înainte de a o trimite din nou.'},
 de:{email:'E-Mail-Bestätigung erforderlich',received:'Ihre Anfrage zur E-Mail-Bestätigung wurde angenommen. Prüfen Sie Posteingang und Spamordner. Wenn Ihr Konto bereits bestätigt ist, melden Sie sich an; eine erneute Registrierung versendet möglicherweise keine weitere E-Mail.',notSubmitted:'Der Organisationsantrag ist noch nicht eingereicht. Bestätigen Sie Ihre E-Mail, melden Sie sich an, fügen Sie die Vollmachtsnachweise bei und reichen Sie den Antrag zur manuellen Prüfung ein.',confirmed:'Ihre E-Mail ist bestätigt. Ihr Organisationsantrag ist noch nicht eingereicht.',pending:'Ihr Antrag ist eingegangen und wartet auf die Prüfung durch einen Administrator. Die Bearbeitung bleibt gesperrt. Hier sehen Sie den Status und mögliche Nachfragen.',progress:['Anmeldedaten erstellen','E-Mail bestätigen und Nachweise beifügen','Zur manuellen Prüfung einreichen','Entscheidung des Administrators abwarten'],working:'Ihre Anfrage wird gesendet…',resend:'Bestätigungs-E-Mail erneut senden',resendIntro:'Keine Bestätigung erhalten? Geben Sie die bei der Registrierung verwendete Adresse ein. Bereits bestätigte Konten können sich anmelden.',resent:'Die Bestätigungsanfrage wurde angenommen. Falls die Adresse berechtigt ist, prüfen Sie Posteingang und Spamordner. Bereits bestätigte Konten sollten sich anmelden.',rate:'Der E-Mail-Dienst begrenzt die Anfragen. Warten Sie vor einem weiteren Versuch. Wenn Ihr Konto bereits bestätigt ist, melden Sie sich an.',unauthorized:'Der vorläufige Supabase-E-Mail-Dienst kann diese Adresse nicht erreichen. Verwenden Sie in dieser Testphase eine im NERUMA-Projekt berechtigte Adresse. Öffentlicher E-Mail-Versand benötigt unseren eigenen SMTP-Dienst.',unconfirmed:'Bestätigen Sie Ihre E-Mail vor der Anmeldung. Unten können Sie eine neue Bestätigung anfordern.',emailError:'Die E-Mail-Anfrage wurde nicht abgeschlossen. Es wurde kein Organisationsantrag eingereicht. Versuchen Sie es später oder melden Sie sich mit Ihrem bestätigten Konto an.',loginError:'Anmeldung fehlgeschlagen. Prüfen Sie E-Mail und Passwort und bestätigen Sie zuerst Ihre E-Mail.',requestError:'Ihr Organisationsantrag wurde nicht eingereicht. Prüfen Sie die hochgeladenen Nachweise und laden Sie die Seite bei Änderungen neu.',stale:'Ihr Organisationsantrag wurde geändert. Laden Sie die Seite vor dem erneuten Einreichen neu.'},
};
export const getAuthFeedback=(locale:Locale)=>copy[locale];
export function authErrorMessage(locale:Locale,code:string|undefined,login=false) {
 const t=getAuthFeedback(locale);
 if(['over_email_send_rate_limit','over_request_rate_limit'].includes(code||'')) return t.rate;
 if(code==='email_address_not_authorized') return t.unauthorized;
 if(code==='email_not_confirmed') return t.unconfirmed;
 return login?t.loginError:t.emailError;
}
