import type { Locale } from './i18n';
export type ContentPage={title:string;intro:string;sections:{heading:string;body:string;items?:string[]}[]};
export const contentPages=['how-it-works','for-organisations','methodology','privacy','terms','accessibility'] as const;
const en:Record<(typeof contentPages)[number],ContentPage>={
 'how-it-works':{title:'A clearer visit, from the first step.',intro:'VIANORAE turns structured information about a place into a guide you can explore before you arrive.',sections:[
 {heading:'1. Describe the spaces',body:'The organisation chooses a Museum template, adds the visit zones, and describes arrival, access and sensory conditions. Photos in a live guide will include alternative text and rights information.'},
 {heading:'2. Keep the source visible',body:'Every guide distinguishes information provided by the venue from an on-site assessment or an independent audit. The source, dates and methodology version matter as much as the description.'},
 {heading:'3. Explore at your own pace',body:'Visitors open the web guide or scan a stable QR code. Each step contains an image, short factual text and sensory information. You can move back, skip a space or review general information without creating an account.'},
 {heading:'4. Keep the guide current',body:'The live platform will retain published versions and assessment history. Updating a guide must not turn an unverified claim into a verified one. A stable QR route will lead to the current published version.'}]},
 'for-organisations':{title:'Help visitors understand your place.',intro:'A consistent Guide Builder for museums and cultural spaces. Start with clear information about the visit you can actually describe.',sections:[
 {heading:'A structured guide, maintained by your team',body:'Describe three to eight zones using the Museum template. Include the entrance, reception, exhibition spaces and somewhere to pause. Arrange them in visit order and preview the visitor experience.',items:['Arrival, step-free routes, lifts, toilets and orientation','Sound, light, smell, crowding, temperature and visual complexity','Quiet spaces, quieter times, equipment and staff support','Source labels, translations and version history']},
 {heading:'Clear responsibilities',body:'Organisation owners manage members. Admins manage places and publish guides. Editors prepare content. Assessors and reviewers will work on assigned evaluations with a separate provenance record.'},
 {heading:'What the foundation demonstrates',body:'The demo includes a browser-local Guide Builder with photographs, a draft preview and a public Museum example. Organisation registration has a dedicated page; real accounts require the separate database connection. Uploaded photographs remain in this browser. Live publishing is not enabled. No subscriptions or paid services are active.'},
 {heading:'Pilot before promises',body:'The plan calls for feedback from three to five locations and people with different sensory needs. The methodology, translations and accessibility must be reviewed before a real public pilot.'}]},
 'methodology':{title:'Describe the environment. Respect the decision.',intro:'The working methodology makes the origin and limits of information visible. VIANORAE does not certify places or assign one accessibility score.',sections:[
 {heading:'Three sources of information',body:'Venue provided means the organisation supplied the information. On-site verified requires a trained assessor following a recorded protocol. Independent audit adds external evidence and a separate reviewer. The demo only uses fictional venue-provided information.'},
 {heading:'Seven channels, without a universal verdict',body:'We describe sound, light, smell, crowding, temperature / air, visual complexity and predictability. The first six use low, moderate, high, variable or not recorded. Predictability is recorded through factual visit steps and orientation information.',items:['Unknown is different from low. Missing data must remain visible.','Subjective bands are observations, not calibrated measurement thresholds.','Raw dB(A), lux and temperature measurements remain separate, with instrument and timestamp.','Conditions can vary by time, event or season.']},
 {heading:'Provenance and expiry',body:'Live assessments will record the method, assessor, assessment date, validity, instruments, protocol version and reviewer where applicable. An expired assessment must retain its history and show that re-assessment is due.'},
 {heading:'Reference points',body:'The platform plan draws on the NYU Sensory Resources Guide for Museums, PAS 6463:2022, A11yJSON / Sozialhelden and WCAG 2.2. These are reference points, not endorsements or a claim of certified compliance.'},
 {heading:'Working status',body:'This implementation follows the VIANORAE platform plan v0.1, dated 6 October 2026. Methodological calibration, lived-experience review and field validation remain part of the pilot.'}]},
 'privacy':{title:'Privacy starts with asking for less.',intro:'Preview privacy notice · 6 October 2026. This version describes the demonstration, before live accounts and database services are enabled.',sections:[
 {heading:'Public guides',body:'You can read the guide without an account. We do not ask for a diagnosis, disability profile or precise location. No analytics, advertising or marketing trackers are installed in this application.'},
 {heading:'Data in your browser',body:'Reading preferences, demo drafts and local review records (representative name and date) are stored in your browser, separated by language. Uploaded demo photographs are stored in browser IndexedDB and are not sent to the server. Reset restores the draft; clear this site’s browser data to remove stored media and review records.'},
 {heading:'Contact enquiries',body:'The contact form prepares text to copy. It does not send, persist or log the enquiry in the application. Only enter information you want to share when you send it through your existing contact.'},
 {heading:'Hosting and the next phase',body:'The hosting provider may process technical request data such as IP addresses and logs. Before real accounts or a pilot launch, the project owner must identify the data controller, provide a contact address, define retention periods and review processor agreements. This notice is a development draft.'}]},
 'terms':{title:'Terms for this demonstration.',intro:'Development draft · 6 October 2026. The current site is a foundation preview for review and testing.',sections:[
 {heading:'Fictional content',body:'The Willow Museum, its spaces and all sensory descriptions are fictional. Do not use them to plan a visit to a real location. Illustrations are examples and are not evidence of an actual venue.'},
 {heading:'Information and decisions',body:'VIANORAE describes environments so people can make their own decisions. It does not provide certification or clinical advice. Future real guides will need their source, currency and limitations checked before publication.'},
 {heading:'Demo workspace',body:'Browser-local changes are for experimentation. Saving a draft does not create an account or publish content. There are no active subscriptions, ticketing or payment features.'},
 {heading:'Before launch',body:'The project owner will review final terms, legal identity, privacy and feedback processes before a real public pilot. These draft terms do not replace that review.'}]},
 'accessibility':{title:'Built for clear, calm access.',intro:'WCAG 2.2 AA is the technical target. This preview is not a declaration of full conformance.',sections:[
 {heading:'What is included',body:'The foundation uses semantic landmarks, labelled controls, text alongside sensory indicators, visible keyboard focus, a skip link and responsive layouts. Essential information is never conveyed by colour alone.',items:['No autoplay, essential animation, adverts or visitor account requirement','Keyboard-accessible visit steps and previous / next controls','Reading settings for larger text, dark appearance, high contrast and spacing','Reduced-motion preferences respected']},
 {heading:'What remains to verify',body:'Automated checks and browser testing support the foundation. Manual screen-reader audits, professional translation review and testing with users remain required before the pilot. Future image uploads must include meaningful alternative text.'},
 {heading:'Report an issue',body:'Use Contact to prepare an enquiry describing the page, device and barrier you encountered. This preview does not send messages; share the enquiry through your existing contact with the project owner.'}]}
};
const ro:typeof en={
 'how-it-works':{title:'O vizită mai clară, de la primul pas.',intro:'VIANORAE transformă informațiile structurate despre un loc într-un ghid pe care îl poți explora înainte de sosire.',sections:[{heading:'1. Descrie spațiile',body:'Instituția alege șablonul Museum, adaugă zonele și descrie sosirea, accesul și condițiile senzoriale. Fotografiile unui ghid live vor include text alternativ și drepturi de utilizare.'},{heading:'2. Păstrează sursa vizibilă',body:'Fiecare ghid separă informațiile oferite de instituție de evaluarea la fața locului și de auditul independent. Sursa, data și versiunea metodologiei contează.'},{heading:'3. Explorează în ritmul tău',body:'Vizitatorii deschid ghidul web sau scanează un QR stabil. Fiecare pas are o imagine, text factual scurt și informații senzoriale. Poți reveni, sări o zonă sau consulta informațiile generale fără cont.'},{heading:'4. Actualizează ghidul',body:'Platforma live va păstra versiunile publicate și istoricul evaluărilor. O actualizare nu transformă automat o afirmație neverificată într-una verificată. QR-ul stabil va duce la versiunea publicată curentă.'}]},
 'for-organisations':{title:'Ajută vizitatorii să înțeleagă locul.',intro:'Un Guide Builder consecvent pentru muzee și spații culturale. Începe cu informații clare despre vizită.',sections:[{heading:'Un ghid structurat, administrat de echipă',body:'Descrie trei până la opt zone cu șablonul Museum. Include intrarea, recepția, expozițiile și un loc pentru pauză. Ordonează zonele și verifică experiența vizitatorului.',items:['Sosire, trasee fără trepte, lifturi, toalete și orientare','Sunet, lumină, miros, aglomerație, temperatură și complexitate vizuală','Spații liniștite, intervale mai calme, echipamente și sprijin','Proveniență, traduceri și istoricul versiunilor']},{heading:'Responsabilități clare',body:'Proprietarul organizației gestionează membrii. Administratorii gestionează locații și publică ghiduri. Editorii pregătesc conținutul. Evaluatorii și reviewerii lucrează pe evaluări asignate, cu proveniență separată.'},{heading:'Ce demonstrează fundația',body:'Demo-ul include Guide Builder local cu fotografii, preview pentru draft și un exemplu Museum public. Înscrierea organizațiilor are o pagină dedicată; conturile reale necesită conectarea bazei separate. Fotografiile încărcate rămân în acest browser. Publicarea live nu este activată. Nu există abonamente sau servicii plătite active.'},{heading:'Pilot înainte de promisiuni',body:'Planul prevede feedback de la trei până la cinci locații și persoane cu nevoi senzoriale diferite. Metodologia, traducerile și accesibilitatea vor fi revizuite înainte de pilot.'}]},
 'methodology':{title:'Descriem mediul. Respectăm decizia.',intro:'Metodologia de lucru face vizibile proveniența și limitele informației. VIANORAE nu certifică locuri și nu acordă un scor unic de accesibilitate.',sections:[{heading:'Trei surse de informații',body:'Venue provided înseamnă informații oferite de instituție. On-site verified presupune un evaluator instruit și un protocol înregistrat. Independent audit adaugă dovezi externe și reviewer separat. Demo-ul folosește exclusiv informații fictive oferite de instituție.'},{heading:'Șapte canale, fără verdict universal',body:'Descriem sunetul, lumina, mirosul, aglomerația, temperatura / aerul, complexitatea vizuală și predictibilitatea. Primele șase folosesc redus, moderat, intens, variabil sau neînregistrat. Predictibilitatea se descrie prin pași factuali și orientare.',items:['Necunoscut nu înseamnă redus. Lipsa datelor rămâne vizibilă.','Nivelurile subiective nu reprezintă praguri de măsurare calibrate.','Măsurătorile brute dB(A), lux și temperatură sunt separate, cu instrument și dată.','Condițiile pot varia în funcție de oră, eveniment sau sezon.']},{heading:'Proveniență și expirare',body:'Evaluările live vor păstra metoda, evaluatorul, data, valabilitatea, instrumentele, versiunea protocolului și reviewerul unde este cazul. Istoricul evaluărilor expirate va fi păstrat.'},{heading:'Repere',body:'Planul folosește NYU Sensory Resources Guide for Museums, PAS 6463:2022, A11yJSON / Sozialhelden și WCAG 2.2. Sunt repere, fără susținere oficială sau afirmație de conformitate certificată.'},{heading:'Statut de lucru',body:'Implementarea urmează planul VIANORAE v0.1 din 6 octombrie 2026. Calibrarea metodologiei, consultarea persoanelor cu experiență directă și validarea pe teren rămân pentru pilot.'}]},
 'privacy':{title:'Confidențialitatea începe cu mai puține date.',intro:'Notă de confidențialitate pentru preview · 6 octombrie 2026. Descrie demo-ul înainte de activarea conturilor și bazei live.',sections:[{heading:'Ghiduri publice',body:'Poți citi fără cont. Nu solicităm diagnostic, profil de dizabilitate sau localizare precisă. Aplicația nu include analytics, reclame sau tracking de marketing.'},{heading:'Date în browser',body:'Preferințele de lectură, drafturile și verificările locale (nume și dată) sunt salvate în browser, separat pe limbi. Fotografiile demo sunt stocate în IndexedDB și nu sunt trimise serverului. Resetarea restaurează draftul; șterge datele acestui site din browser pentru a elimina imaginile și verificările locale.'},{heading:'Solicitări de contact',body:'Formularul pregătește text pentru copiere. Aplicația nu trimite, nu persistă și nu înregistrează solicitarea. Introdu doar informațiile pe care vrei să le distribui.'},{heading:'Hosting și etapa următoare',body:'Furnizorul de hosting poate procesa date tehnice precum IP și loguri. Înainte de conturi reale sau pilot, inițiatorul va identifica operatorul de date, contactul, retenția și acordurile cu furnizorii. Această notă este un draft.'}]},
 'terms':{title:'Termeni pentru demonstrație.',intro:'Draft de dezvoltare · 6 octombrie 2026. Site-ul este un preview pentru verificare și testare.',sections:[{heading:'Conținut fictiv',body:'Muzeul Willow, spațiile și descrierile senzoriale sunt fictive. Nu le folosi pentru a planifica o vizită reală. Ilustrațiile nu sunt dovezi despre o instituție.'},{heading:'Informații și decizii',body:'VIANORAE descrie medii pentru decizii proprii. Nu oferă certificare sau sfaturi clinice. Ghidurile reale vor necesita verificarea provenienței, actualității și limitelor.'},{heading:'Spațiu demo',body:'Modificările locale sunt pentru experimentare. Salvarea draftului nu creează cont și nu publică. Nu există abonamente, ticketing sau plăți active.'},{heading:'Înainte de lansare',body:'Inițiatorul va revizui termenii finali, identitatea juridică, confidențialitatea și feedback-ul înainte de un pilot real. Acest draft nu înlocuiește revizuirea.'}]},
 'accessibility':{title:'Acces clar și calm.',intro:'Ținta tehnică este WCAG 2.2 AA. Acest preview nu declară conformitate completă.',sections:[{heading:'Ce include',body:'Fundația folosește structură semantică, controale etichetate, indicatori însoțiți de text, focus vizibil, link de salt și layout responsive. Informația esențială nu se transmite doar prin culoare.',items:['Fără autoplay, animație esențială, reclame sau cont de vizitator','Pași și butoane anterior / următor accesibile din tastatură','Text mai mare, mod întunecat, contrast și spațiere','Respectarea preferinței pentru mișcare redusă']},{heading:'Ce mai verificăm',body:'Testele automate și verificările în browser susțin fundația. Auditul manual cu screen reader, traducerile profesionale și testele cu utilizatori rămân necesare înainte de pilot.'},{heading:'Raportează o problemă',body:'Folosește Contact pentru o solicitare cu pagina, dispozitivul și bariera întâlnită. Preview-ul nu trimite mesaje; distribuie solicitarea prin contactul existent.'}]}
};
const de:typeof en={
 'how-it-works':{title:'Ein klarerer Besuch, vom ersten Schritt.',intro:'VIANORAE macht aus strukturierten Ortsinformationen einen Guide für die Zeit vor Ihrer Ankunft.',sections:[{heading:'1. Räume beschreiben',body:'Die Organisation wählt die Museum-Vorlage und beschreibt Besuchszonen, Ankunft, Zugang und sensorische Bedingungen. Fotos im Live-Guide erhalten Alternativtexte und Nutzungsrechte.'},{heading:'2. Quellen sichtbar halten',body:'Ein Guide unterscheidet Angaben der Einrichtung, Vor-Ort-Prüfungen und unabhängige Audits. Quelle, Datum und Methodikversion sind entscheidend.'},{heading:'3. Im eigenen Tempo entdecken',body:'Öffnen Sie den Web-Guide oder scannen Sie einen stabilen QR-Code. Jeder Schritt enthält ein Bild, kurze Fakten und sensorische Angaben. Zurückgehen, überspringen und allgemeine Informationen sind ohne Konto möglich.'},{heading:'4. Aktuell halten',body:'Die Live-Plattform wird Versionen und Prüfverläufe erhalten. Eine Aktualisierung macht eine ungeprüfte Angabe nicht automatisch zu einer geprüften. Die stabile QR-Route führt zur aktuellen veröffentlichten Version.'}]},
 'for-organisations':{title:'Helfen Sie Gästen, Ihren Ort zu verstehen.',intro:'Ein einheitlicher Guide Builder für Museen und Kulturorte. Beginnen Sie mit klaren, beschreibbaren Informationen.',sections:[{heading:'Ein strukturierter Guide für Ihr Team',body:'Beschreiben Sie drei bis acht Zonen mit der Museum-Vorlage: Eingang, Empfang, Ausstellungsräume und Pausenraum. Ordnen Sie die Schritte und prüfen Sie die Vorschau.',items:['Ankunft, stufenlose Wege, Aufzüge, Toiletten und Orientierung','Geräusche, Licht, Gerüche, Andrang, Temperatur und visuelle Komplexität','Ruhige Räume, ruhigere Zeiten, Hilfsmittel und Unterstützung','Quellen, Übersetzungen und Versionsverlauf']},{heading:'Klare Verantwortlichkeiten',body:'Eigentümer verwalten Mitglieder. Administratoren verwalten Orte und veröffentlichen Guides. Redakteure bereiten Inhalte vor. Prüfende und Reviewer bearbeiten zugewiesene Bewertungen.'},{heading:'Was die Grundlage zeigt',body:'Die Demo enthält einen lokalen Guide Builder mit Fotos, eine Entwurfsvorschau und ein öffentliches Museum-Beispiel. Die Organisationsregistrierung hat eine eigene Seite; echte Konten benötigen die separate Datenbank. Fotos bleiben in diesem Browser. Live-Veröffentlichung ist nicht aktiv. Keine kostenpflichtigen Dienste sind aktiv.'},{heading:'Pilot vor Versprechen',body:'Der Plan sieht Rückmeldungen von drei bis fünf Orten und Menschen mit unterschiedlichen sensorischen Bedürfnissen vor. Methodik, Übersetzungen und Barrierefreiheit werden vor dem Pilot geprüft.'}]},
 'methodology':{title:'Die Umgebung beschreiben. Die Entscheidung respektieren.',intro:'Die Arbeitsmethodik macht Herkunft und Grenzen sichtbar. VIANORAE zertifiziert keine Orte und vergibt keine Gesamtnote für Barrierefreiheit.',sections:[{heading:'Drei Informationsquellen',body:'Venue provided bedeutet Angaben der Einrichtung. On-site verified erfordert geschulte Prüfende und ein dokumentiertes Protokoll. Independent audit ergänzt externe Nachweise und einen separaten Reviewer. Die Demo nutzt nur fiktive Angaben der Einrichtung.'},{heading:'Sieben Kanäle, kein allgemeines Urteil',body:'Wir beschreiben Geräusche, Licht, Geruch, Andrang, Temperatur / Luft, visuelle Komplexität und Vorhersehbarkeit. Die ersten sechs nutzen gering, mittel, intensiv, wechselnd oder nicht erfasst. Vorhersehbarkeit wird durch Besuchsschritte und Orientierung beschrieben.',items:['Unbekannt bedeutet nicht gering. Fehlende Daten bleiben sichtbar.','Subjektive Stufen sind keine kalibrierten Messgrenzen.','Rohwerte in dB(A), Lux und Grad bleiben getrennt, mit Gerät und Zeitpunkt.','Bedingungen können nach Uhrzeit, Veranstaltung und Saison variieren.']},{heading:'Herkunft und Gültigkeit',body:'Live-Prüfungen speichern Methode, prüfende Person, Datum, Gültigkeit, Geräte, Protokollversion und gegebenenfalls Reviewer. Abgelaufene Prüfungen bleiben im Verlauf sichtbar.'},{heading:'Referenzen',body:'Der Plan nutzt NYU Sensory Resources Guide for Museums, PAS 6463:2022, A11yJSON / Sozialhelden und WCAG 2.2. Das sind Referenzen, keine Empfehlungen durch diese Stellen oder zertifizierte Konformität.'},{heading:'Arbeitsstand',body:'Diese Grundlage folgt dem VIANORAE-Plan v0.1 vom 6. Oktober 2026. Kalibrierung, Prüfung durch Menschen mit eigener Erfahrung und Feldvalidierung gehören zum Pilot.'}]},
 'privacy':{title:'Datenschutz beginnt mit weniger Fragen.',intro:'Datenschutzhinweis zur Vorschau · 6. Oktober 2026. Diese Fassung beschreibt die Demo vor Live-Konten und Datenbank.',sections:[{heading:'Öffentliche Guides',body:'Lesen ist ohne Konto möglich. Wir fragen weder Diagnose noch Behinderungsprofil oder genauen Standort ab. Die Anwendung enthält keine Analyse-, Werbe- oder Marketingtracker.'},{heading:'Daten im Browser',body:'Leseeinstellungen, Demo-Entwürfe und lokale Prüfungen (Name und Datum) werden im Browser gespeichert. Demo-Fotos liegen in IndexedDB und werden nicht an den Server gesendet. Löschen Sie die Browserdaten dieser Website, um Bilder und lokale Prüfungen zu entfernen. Nutzen Sie Zurücksetzen für die Standardwerte. Die Daten werden nicht an eine Datenbank gesendet.'},{heading:'Kontaktanfragen',body:'Das Formular bereitet Text zum Kopieren vor. Die Anwendung sendet, speichert oder protokolliert die Anfrage nicht. Tragen Sie nur Informationen ein, die Sie teilen möchten.'},{heading:'Hosting und nächste Phase',body:'Der Hostinganbieter kann technische Anfragedaten wie IP-Adressen und Logs verarbeiten. Vor echten Konten und dem Pilot müssen Verantwortliche, Kontakt, Aufbewahrung und Auftragsverarbeitung festgelegt werden. Dieser Hinweis ist ein Entwicklungsentwurf.'}]},
 'terms':{title:'Bedingungen für diese Demonstration.',intro:'Entwicklungsentwurf · 6. Oktober 2026. Diese Website ist eine Vorschau zur Prüfung und Erprobung.',sections:[{heading:'Fiktive Inhalte',body:'Das Willow Museum, seine Räume und sensorischen Angaben sind fiktiv. Nutzen Sie sie nicht für einen echten Besuch. Illustrationen sind keine Nachweise für eine reale Einrichtung.'},{heading:'Informationen und Entscheidungen',body:'VIANORAE beschreibt Umgebungen für eigene Entscheidungen. Es bietet keine Zertifizierung oder klinische Beratung. Echte Guides erfordern die Prüfung von Herkunft, Aktualität und Grenzen.'},{heading:'Demo-Arbeitsbereich',body:'Lokale Änderungen dienen dem Ausprobieren. Speichern erstellt kein Konto und veröffentlicht nichts. Keine Abonnements, Tickets oder Zahlungen sind aktiv.'},{heading:'Vor dem Start',body:'Vor einem echten Pilot werden endgültige Bedingungen, rechtliche Identität, Datenschutz und Feedbackprozesse geprüft. Dieser Entwurf ersetzt die Prüfung nicht.'}]},
 'accessibility':{title:'Für einen klaren, ruhigen Zugang.',intro:'Das technische Ziel ist WCAG 2.2 AA. Diese Vorschau erklärt keine vollständige Konformität.',sections:[{heading:'Enthaltene Funktionen',body:'Die Grundlage nutzt semantische Bereiche, beschriftete Bedienelemente, Text neben sensorischen Angaben, sichtbaren Tastaturfokus, einen Sprunglink und flexible Layouts. Wesentliche Informationen werden nicht allein durch Farbe vermittelt.',items:['Kein Autoplay, notwendige Animation, Werbung oder Besucherkonto','Besuchsschritte und Zurück / Weiter per Tastatur','Größere Schrift, dunkle Darstellung, Kontrast und Textabstand','Beachtung reduzierter Bewegung']},{heading:'Weitere Prüfungen',body:'Automatische und Browsertests unterstützen die Grundlage. Manuelle Screenreader-Prüfungen, professionelle Übersetzungsprüfung und Nutzertests bleiben vor dem Pilot erforderlich.'},{heading:'Problem melden',body:'Bereiten Sie unter Kontakt eine Anfrage mit Seite, Gerät und Barriere vor. Die Vorschau sendet nicht; teilen Sie die Anfrage über Ihren bestehenden Kontakt.'}]}
};
export function getContent(locale:Locale,page:string):ContentPage|undefined {return ({en,ro,de}[locale] as Record<string,ContentPage>)[page];}
export const references=[
 ['NYU Sensory Resources Guide for Museums','https://wp.nyu.edu/sensory_resources_guide_for_museums/sensory-guide/'],
 ['PAS 6463:2022 — Design for the mind','https://knowledge.bsigroup.com/products/design-for-the-mind-neurodiversity-and-the-built-environment-guide'],
 ['A11yJSON / Sozialhelden','https://github.com/sozialhelden/a11yjson'],
 ['WCAG 2.2','https://www.w3.org/TR/WCAG22/']
];
