import type { Locale } from './i18n';
export const EVIDENCE_BUCKET='vianorae-mandate-evidence';
export const MAX_EVIDENCE_BYTES=3*1024*1024;
export type MandateDocument={id:string;filename:string;mime_type:string;byte_size:number;application_id:string|null;storage_key:string;uploaded_at:string|null};
const copy={
 en:{title:'Documents confirming your mandate',hint:'Attach a signed authorisation, appointment letter or an official document naming you as the authorised representative. PDF, JPG or PNG; up to 3 files, 3 MB each. Only you and platform administrators reviewing your request can access these files. Redact unrelated personal information; do not upload identity cards or passports.',afterEmail:'Step 2: after confirming your email, sign in to upload these documents and submit your request. Files are not sent with the initial sign-up.',upload:'Upload mandate document',busy:'Uploading privately…',uploaded:'Document uploaded privately.',remove:'Remove from this submission',error:'Upload failed. Use a PDF, JPG or PNG under 3 MB. If you reach the upload limit, contact administration.',required:'Upload at least one mandate document before submitting.',download:'Download document',reviewed:'I opened and checked this mandate document:',missing:'No mandate documents attached. Request more information before approving.',setup:'Private document upload is being activated. Please return shortly to submit your request.'},
 ro:{title:'Documente care confirmă mandatul',hint:'Atașează o împuternicire semnată, o decizie de numire sau un document oficial care te identifică drept reprezentant autorizat. PDF, JPG sau PNG; maximum 3 fișiere, câte 3 MB. Fișierele sunt accesibile doar ție și administratorilor platformei care verifică cererea. Acoperă datele personale fără legătură cu mandatul; nu încărca buletine sau pașapoarte.',afterEmail:'Pasul 2: după confirmarea emailului, autentifică-te pentru a încărca documentele și a trimite cererea. Fișierele nu se trimit la înregistrarea inițială.',upload:'Încarcă documentul de mandat',busy:'Încărcare privată în curs…',uploaded:'Document încărcat privat.',remove:'Elimină din această cerere',error:'Încărcarea a eșuat. Folosește un PDF, JPG sau PNG sub 3 MB. Dacă ai atins limita de încărcări, contactează administrația.',required:'Încarcă cel puțin un document de mandat înainte de trimitere.',download:'Descarcă documentul',reviewed:'Am deschis și verificat acest document de mandat:',missing:'Nu sunt atașate documente de mandat. Cere completări înainte de aprobare.',setup:'Activăm încărcarea privată a documentelor. Revino în curând pentru a trimite cererea.'},
 de:{title:'Nachweise Ihrer Vertretungsbefugnis',hint:'Fügen Sie eine unterschriebene Vollmacht, eine Ernennungsurkunde oder ein offizielles Dokument bei, das Sie als bevollmächtigte Person benennt. PDF, JPG oder PNG; bis zu 3 Dateien mit jeweils 3 MB. Nur Sie und die prüfenden Plattformadministratoren können darauf zugreifen. Schwärzen Sie nicht erforderliche personenbezogene Angaben; keine Ausweise oder Reisepässe hochladen.',afterEmail:'Schritt 2: Bestätigen Sie Ihre E-Mail und melden Sie sich an, um die Nachweise hochzuladen und den Antrag einzureichen. Bei der ersten Registrierung werden keine Dateien versendet.',upload:'Vollmachtsnachweis hochladen',busy:'Privater Upload läuft…',uploaded:'Nachweis privat hochgeladen.',remove:'Aus diesem Antrag entfernen',error:'Upload fehlgeschlagen. Verwenden Sie PDF, JPG oder PNG unter 3 MB. Bei Erreichen des Uploadlimits wenden Sie sich an die Administration.',required:'Laden Sie vor dem Einreichen mindestens einen Vollmachtsnachweis hoch.',download:'Nachweis herunterladen',reviewed:'Ich habe diesen Vollmachtsnachweis geöffnet und geprüft:',missing:'Keine Vollmachtsnachweise beigefügt. Fordern Sie vor der Genehmigung weitere Informationen an.',setup:'Der private Dokumentenupload wird aktiviert. Bitte kommen Sie in Kürze zurück, um Ihren Antrag einzureichen.'},
};
export const getEvidenceCopy=(locale:Locale)=>copy[locale];
