import type { Locale } from './i18n';

const copy = {
  en: {
    register: 'Create an organisation account', login: 'Sign in',
    accountIntro: 'For museums, hotels, cultural spaces and other organisations that maintain visitor information.',
    unavailable: 'Registration is not active yet. This form does not create an account or send your details. You can explore the demo workspace.',
    organisation: 'Organisation name', type: 'Organisation type', representative: 'Responsible representative',
    email: 'Work email', password: 'Password', passwordHint: 'Use at least 12 characters.',
    types: ['Institution', 'Museum', 'Hotel', 'Cultural venue', 'Public service', 'Other organisation'],
    responsibilityTitle: 'Your information can change someone’s experience.',
    responsibilityBody: 'For someone who has stopped visiting unfamiliar places, a clear, honest guide can make a first visit possible again. A missing detail about a loud sound, a queue or a closed quiet room can change that experience just as much. Describe what visitors will actually encounter, including difficulties and uncertainty.',
    responsibilityScope: 'Your organisation takes full responsibility for the accuracy, completeness and currency of the information and images it provides, and for its right to use those images. Name a person who checks the guide and updates it when conditions change. VIANORAE provides the platform; it does not turn venue information into an independent assessment.',
    commitments: ['Describe observed conditions and disclose what you do not know.', 'Check the route, photographs, sensory details and available support.', 'Correct errors and update the guide when conditions change.'],
    authority: 'I am authorised to represent this organisation.',
    accept: 'On behalf of my organisation, I accept responsibility for the content we provide and for keeping it accurate and up to date.',
    sensitive: 'Use photographs without identifiable visitors whenever possible. Do not upload images of people without the necessary permission.',
    photo: 'Upload a zone photograph', photoHint: 'JPEG, PNG or WebP · up to 5 MB. In the demo, images stay in this browser and are saved with your draft.',
    photoAlt: 'Image description (alternative text)', photoRights: 'Image rights / credit', photoDate: 'Date photographed',
    photoRightsHint: 'For example: photograph taken by our team; permission held by the organisation.',
    removePhoto: 'Remove photograph from draft', processing: 'Preparing image…', photoAdded: 'Photograph added locally. Complete its details and save the draft.',
    invalidPhoto: 'Choose a valid JPEG, PNG or WebP image of no more than 5 MB.',
    photoFailed: 'The image could not be prepared or stored in this browser. Your previous image is unchanged.',
    photoMissing: 'The saved photograph is unavailable in this browser. Choose the file again.',
    reviewTitle: 'Review before publication', checkedOn: 'Content checked on',
    reviewIntro: 'Saving a draft is not publishing it. Check the visitor experience and confirm responsibility for this version before live publication.',
    checkContent: 'I have checked the route, descriptions and sensory information against the current conditions.',
    checkImages: 'The photographs represent the spaces, have useful descriptions, and we hold the necessary rights and permissions.',
    reviewButton: 'Check this draft for publication', reviewPassed: 'Review recorded for this saved draft in this browser. It has not been published. Any edit requires a new review.',
    reviewUnsaved: 'Save this version of the draft before recording the review.',
    savedLocally: 'This review stays in this browser. Live publishing is not enabled in the demo.',
    account: 'Organisation account', onboarding: 'Set up your organisation', createOrganisation: 'Create organisation',
    confirmation: 'If this address is eligible, check your email for a confirmation link before signing in.',
    authError: 'The request could not be completed. Check your details and try again.',
    invalidFields: 'Complete the required fields and confirm the organisation’s responsibilities.',
    signOut: 'Sign out', liveBoundary: 'Your organisation account is separate from the local demo editor. Database-backed guide editing and publishing are the next stage.',
  },
  ro: {
    register: 'Creează un cont de organizație', login: 'Autentificare',
    accountIntro: 'Pentru muzee, hoteluri, spații culturale și alte organizații care întrețin informațiile pentru vizitatori.',
    unavailable: 'Înscrierile nu sunt încă active. Acest formular nu creează un cont și nu trimite datele tale. Poți explora spațiul demo.',
    organisation: 'Numele organizației', type: 'Tipul organizației', representative: 'Reprezentant responsabil',
    email: 'Email profesional', password: 'Parolă', passwordHint: 'Folosește cel puțin 12 caractere.',
    types: ['Instituție', 'Muzeu', 'Hotel', 'Spațiu cultural', 'Serviciu public', 'Altă organizație'],
    responsibilityTitle: 'Informațiile tale pot schimba experiența cuiva.',
    responsibilityBody: 'Pentru cineva care a renunțat să viziteze locuri necunoscute, un ghid clar și sincer poate face din nou posibilă o primă vizită. Un detaliu omis despre un sunet puternic, o coadă sau o cameră liniștită închisă poate schimba la fel de mult acea experiență. Descrie ce vor întâlni efectiv vizitatorii, inclusiv dificultățile și incertitudinile.',
    responsibilityScope: 'Organizația ta își asumă întreaga responsabilitate pentru corectitudinea, completitudinea și actualitatea informațiilor și imaginilor pe care le furnizează, precum și pentru dreptul de utilizare a imaginilor. Desemnează o persoană care verifică ghidul și îl actualizează când condițiile se schimbă. VIANORAE oferă platforma; informația instituției nu devine automat o evaluare independentă.',
    commitments: ['Descrie condițiile observate și spune clar ce nu știi.', 'Verifică traseul, fotografiile, detaliile senzoriale și sprijinul disponibil.', 'Corectează erorile și actualizează ghidul când condițiile se schimbă.'],
    authority: 'Sunt autorizat să reprezint această organizație.',
    accept: 'În numele organizației, îmi asum responsabilitatea pentru conținutul furnizat și pentru menținerea lui corectă și actualizată.',
    sensitive: 'Folosește, pe cât posibil, fotografii fără vizitatori identificabili. Nu încărca imagini cu persoane fără permisiunile necesare.',
    photo: 'Încarcă o fotografie a zonei', photoHint: 'JPEG, PNG sau WebP · maximum 5 MB. În demo, imaginile rămân în acest browser și se salvează împreună cu draftul.',
    photoAlt: 'Descrierea imaginii (text alternativ)', photoRights: 'Drepturi de utilizare / credit', photoDate: 'Data fotografiei',
    photoRightsHint: 'De exemplu: fotografie realizată de echipa noastră; organizația deține permisiunea de utilizare.',
    removePhoto: 'Elimină fotografia din draft', processing: 'Pregătim imaginea…', photoAdded: 'Fotografia a fost adăugată local. Completează detaliile și salvează draftul.',
    invalidPhoto: 'Alege o imagine JPEG, PNG sau WebP validă de maximum 5 MB.',
    photoFailed: 'Imaginea nu a putut fi pregătită sau stocată în acest browser. Imaginea anterioară a rămas neschimbată.',
    photoMissing: 'Fotografia salvată nu este disponibilă în acest browser. Alege din nou fișierul.',
    reviewTitle: 'Verificare înainte de publicare', checkedOn: 'Conținut verificat la data de',
    reviewIntro: 'Salvarea unui draft nu înseamnă publicare. Verifică experiența vizitatorului și confirmă responsabilitatea pentru această versiune înainte de publicarea live.',
    checkContent: 'Am verificat traseul, descrierile și informațiile senzoriale în raport cu condițiile actuale.',
    checkImages: 'Fotografiile reprezintă spațiile, au descrieri utile și deținem drepturile și permisiunile necesare.',
    reviewButton: 'Verifică acest draft pentru publicare', reviewPassed: 'Verificare înregistrată pentru acest draft salvat, în acest browser. Ghidul nu a fost publicat. Orice modificare necesită o nouă verificare.',
    reviewUnsaved: 'Salvează această versiune a draftului înainte să înregistrezi verificarea.',
    savedLocally: 'Această verificare rămâne în browser. Publicarea live nu este activată în demo.',
    account: 'Contul organizației', onboarding: 'Configurează organizația', createOrganisation: 'Creează organizația',
    confirmation: 'Dacă această adresă este eligibilă, verifică emailul pentru confirmare înainte de autentificare.',
    authError: 'Solicitarea nu a putut fi finalizată. Verifică datele și încearcă din nou.',
    invalidFields: 'Completează câmpurile obligatorii și confirmă responsabilitățile organizației.',
    signOut: 'Deconectare', liveBoundary: 'Contul organizației este separat de editorul demo local. Editarea ghidurilor în baza de date și publicarea lor sunt etapa următoare.',
  },
  de: {
    register: 'Organisationskonto erstellen', login: 'Anmelden',
    accountIntro: 'Für Museen, Hotels, Kulturorte und andere Organisationen, die Besucherinformationen pflegen.',
    unavailable: 'Die Registrierung ist noch nicht aktiv. Dieses Formular erstellt kein Konto und sendet keine Daten. Sie können den Demo-Arbeitsbereich erkunden.',
    organisation: 'Name der Organisation', type: 'Art der Organisation', representative: 'Verantwortliche Vertretung',
    email: 'Geschäftliche E-Mail', password: 'Passwort', passwordHint: 'Verwenden Sie mindestens 12 Zeichen.',
    types: ['Institution', 'Museum', 'Hotel', 'Kulturort', 'Öffentlicher Dienst', 'Andere Organisation'],
    responsibilityTitle: 'Ihre Informationen können das Erlebnis eines Menschen verändern.',
    responsibilityBody: 'Für jemanden, der unbekannte Orte nicht mehr besucht, kann ein klarer, ehrlicher Guide einen ersten Besuch wieder möglich machen. Ein fehlender Hinweis auf laute Geräusche, eine Warteschlange oder einen geschlossenen Ruheraum kann dieses Erlebnis ebenso verändern. Beschreiben Sie die tatsächlichen Bedingungen, einschließlich Schwierigkeiten und Unsicherheiten.',
    responsibilityScope: 'Ihre Organisation übernimmt die volle Verantwortung für Richtigkeit, Vollständigkeit und Aktualität der bereitgestellten Informationen und Bilder sowie für deren Nutzungsrechte. Benennen Sie eine Person, die den Guide prüft und bei Änderungen aktualisiert. VIANORAE stellt die Plattform bereit; Angaben des Ortes werden dadurch nicht zu einer unabhängigen Bewertung.',
    commitments: ['Beschreiben Sie beobachtete Bedingungen und benennen Sie Unbekanntes.', 'Prüfen Sie Route, Fotos, sensorische Angaben und verfügbare Unterstützung.', 'Korrigieren und aktualisieren Sie den Guide bei veränderten Bedingungen.'],
    authority: 'Ich bin berechtigt, diese Organisation zu vertreten.',
    accept: 'Im Namen meiner Organisation übernehme ich die Verantwortung für unsere Inhalte und deren Richtigkeit und Aktualität.',
    sensitive: 'Verwenden Sie möglichst Fotos ohne identifizierbare Besucher. Laden Sie keine Personenbilder ohne die erforderliche Erlaubnis hoch.',
    photo: 'Foto des Bereichs hochladen', photoHint: 'JPEG, PNG oder WebP · bis 5 MB. Im Demo bleiben Bilder in diesem Browser und werden mit dem Entwurf gespeichert.',
    photoAlt: 'Bildbeschreibung (Alternativtext)', photoRights: 'Bildrechte / Urheberangabe', photoDate: 'Aufnahmedatum',
    photoRightsHint: 'Zum Beispiel: Aufnahme unseres Teams; Nutzungsrecht liegt bei der Organisation.',
    removePhoto: 'Foto aus dem Entwurf entfernen', processing: 'Bild wird vorbereitet…', photoAdded: 'Foto lokal hinzugefügt. Ergänzen Sie die Angaben und speichern Sie den Entwurf.',
    invalidPhoto: 'Wählen Sie ein gültiges JPEG-, PNG- oder WebP-Bild mit höchstens 5 MB.',
    photoFailed: 'Das Bild konnte in diesem Browser nicht verarbeitet oder gespeichert werden. Das vorherige Bild bleibt erhalten.',
    photoMissing: 'Das gespeicherte Foto ist in diesem Browser nicht verfügbar. Wählen Sie die Datei erneut.',
    reviewTitle: 'Prüfung vor der Veröffentlichung', checkedOn: 'Inhalte geprüft am',
    reviewIntro: 'Ein gespeicherter Entwurf ist noch nicht veröffentlicht. Prüfen Sie das Besuchserlebnis und bestätigen Sie die Verantwortung für diese Version vor der Veröffentlichung.',
    checkContent: 'Ich habe Route, Beschreibungen und sensorische Angaben anhand der aktuellen Bedingungen geprüft.',
    checkImages: 'Die Fotos zeigen die Räume, haben hilfreiche Beschreibungen und die erforderlichen Rechte und Genehmigungen liegen vor.',
    reviewButton: 'Diesen Entwurf auf Veröffentlichungsbereitschaft prüfen', reviewPassed: 'Prüfung für diesen gespeicherten Entwurf lokal erfasst. Er wurde nicht veröffentlicht. Jede Änderung erfordert eine neue Prüfung.',
    reviewUnsaved: 'Speichern Sie diese Version, bevor Sie die Prüfung erfassen.',
    savedLocally: 'Diese Prüfung bleibt im Browser. Live-Veröffentlichung ist im Demo nicht aktiv.',
    account: 'Organisationskonto', onboarding: 'Organisation einrichten', createOrganisation: 'Organisation erstellen',
    confirmation: 'Wenn diese Adresse berechtigt ist, prüfen Sie Ihre E-Mails zur Bestätigung, bevor Sie sich anmelden.',
    authError: 'Die Anfrage konnte nicht abgeschlossen werden. Prüfen Sie Ihre Angaben und versuchen Sie es erneut.',
    invalidFields: 'Füllen Sie die Pflichtfelder aus und bestätigen Sie die Verantwortung der Organisation.',
    signOut: 'Abmelden', liveBoundary: 'Ihr Organisationskonto ist vom lokalen Demo-Editor getrennt. Datenbankgestützte Bearbeitung und Veröffentlichung folgen im nächsten Schritt.',
  },
};

export const organisationTypes = ['institution', 'museum', 'hotel', 'cultural', 'public_service', 'other'] as const;
export const responsibilityVersion = '2026-10-07-v1';
export const getOrganisationCopy = (locale: Locale) => copy[locale];
