import { test,expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const paths=['','how-it-works','for-organisations','methodology','example-guide','explore','contact','login','privacy','terms','accessibility','dashboard','dashboard/builder','dashboard/preview','dashboard/team','dashboard/settings','dashboard/share','dashboard/locations'];
for(const locale of ['en','ro','de']) {
 test(`${locale}: routes and document language`,async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));for(const path of paths){const response=await page.goto(`/${locale}/${path}`);expect(response?.status(),path).toBe(200);await expect(page.locator('html')).toHaveAttribute('lang',locale);await expect(page.locator('main h1')).toBeVisible();}expect(errors).toEqual([]);});
}
for(const path of ['/en','/en/example-guide','/en/contact','/en/dashboard/builder','/ro','/de']) {
 test(`WCAG A/AA checks ${path}`,async({page})=>{await page.goto(path);const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze();expect(results.violations).toEqual([]);});
}
test('guide navigation, skip and completion work by keyboard',async({page})=>{await page.goto('/en/example-guide');await expect(page.getByRole('heading',{name:'The main entrance',exact:true})).toBeVisible();const next=page.getByRole('button',{name:'Next step',exact:true});await next.focus();await page.keyboard.press('Enter');await expect(page.getByRole('heading',{name:'Reception & the foyer',exact:true})).toBeFocused();await page.getByRole('button',{name:'The quiet room',exact:false}).click();await expect(page.getByRole('heading',{name:'The quiet room',exact:true})).toBeVisible();await page.getByRole('button',{name:'Finish the guide'}).click();await expect(page.getByRole('heading',{name:'You have explored the guide.'})).toBeFocused();await page.getByRole('button',{name:'Start again'}).click();await expect(page.getByRole('heading',{name:'The main entrance',exact:true})).toBeVisible();});
test('local draft persists into preview and public example remains fictional',async({page})=>{await page.goto('/en/dashboard/builder');await page.getByLabel('Zone title',{exact:true}).first().fill('My entrance draft');await page.getByRole('button',{name:'Save draft'}).click();await expect(page.getByRole('status')).toHaveText('Draft saved in this browser.');await page.reload();await expect(page.getByLabel('Zone title',{exact:true}).first()).toHaveValue('My entrance draft');await page.getByRole('link',{name:'Preview your draft',exact:true}).last().click();await expect(page.getByRole('heading',{name:'My entrance draft'})).toBeVisible();await page.goto('/en/example-guide');await expect(page.getByRole('heading',{name:'The main entrance',exact:true})).toBeVisible();await page.goto('/ro/dashboard/builder');await expect(page.getByLabel('Titlul zonei',{exact:true}).first()).toHaveValue('Intrarea principală');});
test('corrupt local draft falls back safely',async({page})=>{await page.goto('/en/dashboard/builder');await page.evaluate(()=>localStorage.setItem('vianorae:demo-draft:v1:en','{"schemaVersion":1,"zones":null}'));await page.reload();await expect(page.getByLabel('Zone title',{exact:true}).first()).toHaveValue('The main entrance');});
test('catalog filters distinguish museum from unavailable categories',async({page})=>{await page.goto('/en/explore');await page.getByLabel('Category',{exact:true}).selectOption('theatre');await expect(page.getByRole('status')).toHaveText('No guide matches these filters.');await page.getByLabel('Category',{exact:true}).selectOption('museum');await expect(page.getByRole('link',{name:'Open guide',exact:true})).toBeVisible();});
test('QR API and stable redirects',async({request})=>{const svg=await request.get('/api/qr/willow-museum?locale=ro&download=1');expect(svg.status()).toBe(200);expect(svg.headers()['content-type']).toContain('image/svg+xml');expect(svg.headers()['content-disposition']).toContain('attachment');expect(await svg.text()).toContain('<svg');const redirect=await request.get('/q/willow-museum?locale=de',{maxRedirects:0});expect(redirect.status()).toBe(307);expect(redirect.headers().location).toContain('/de/places/willow-museum/guide');expect((await request.get('/q/unknown')).status()).toBe(404);expect((await request.get('/api/qr/unknown')).status()).toBe(404);const unsafe=await request.get('/q/willow-museum?locale=https://evil.example',{maxRedirects:0});expect(unsafe.headers().location).toContain('/en/places/');});
test('language switch preserves the current route',async({page})=>{await page.goto('/en/methodology');await page.getByRole('link',{name:'Română',exact:true}).click();await expect(page).toHaveURL(/\/ro\/methodology$/);await expect(page.locator('html')).toHaveAttribute('lang','ro');});
test('contact prepares an enquiry without sending it',async({page})=>{await page.goto('/en/contact');let posted=false;page.on('request',r=>{if(r.method()==='POST')posted=true;});await page.getByLabel('Your name').fill('Demo person');await page.getByLabel('Email').fill('demo@example.invalid');await page.getByLabel('Your message').fill('I would like to discuss the pilot.');await page.getByRole('button',{name:'Copy enquiry'}).click();await expect(page.locator('.enquiry-output')).toContainText('I would like to discuss the pilot.');expect(posted).toBe(false);});
test('reading preferences persist and contrast themes pass automated checks',async({page})=>{await page.goto('/en');await page.getByText('Reading settings',{exact:true}).click();await page.getByLabel('Text size',{exact:true}).selectOption('larger');await page.getByLabel('Appearance',{exact:true}).selectOption('dark');await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await expect(page.locator('html')).toHaveAttribute('data-text-size','larger');let result=await new AxeBuilder({page}).withTags(['wcag2aa']).analyze();expect(result.violations).toEqual([]);await page.getByText('Reading settings',{exact:true}).click();await page.getByLabel('Appearance',{exact:true}).selectOption('contrast');result=await new AxeBuilder({page}).withTags(['wcag2aa']).analyze();expect(result.violations).toEqual([]);});
test('mobile reflow and menu',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/en');await page.getByRole('button',{name:'Open menu'}).click();await expect(page.getByRole('link',{name:'How it works',exact:true})).toBeVisible();await page.getByRole('link',{name:'How it works',exact:true}).click();await expect(page).toHaveURL(/how-it-works$/);for(const path of ['/en','/en/example-guide','/en/dashboard/builder']){await page.goto(path);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),path).toBe(true);}await page.goto('/en');await page.screenshot({path:'docs/mobile-preview.png',fullPage:true});});
test('320px reflow with 200% text and extra spacing',async({page})=>{await page.setViewportSize({width:320,height:800});for(const path of ['/en','/de','/en/example-guide','/en/dashboard/builder']){await page.goto(path);await page.evaluate(()=>{document.documentElement.style.fontSize='32px';document.documentElement.dataset.spacing='true';});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),path).toBe(true);}});
test('desktop visual evidence',async({page})=>{await page.setViewportSize({width:1440,height:1000});await page.goto('/en');await page.screenshot({path:'docs/home-preview.png',fullPage:true});await page.goto('/en/example-guide');await page.screenshot({path:'docs/guide-preview.png',fullPage:true});await page.goto('/en/dashboard');await page.screenshot({path:'docs/workspace-preview.png',fullPage:true});});
