'use client';
import Link from 'next/link';
import { useState, useEffect } from 'react';
import { Save, ArrowUpRight } from 'lucide-react';
import { getCopy,type Locale } from '@/lib/i18n';
import { draftKey,getDemoGuide,parseDraft,type Guide,type SensoryProfile,type SensoryLevel } from '@/lib/demo';
export function DemoBuilder({locale}:{locale:Locale}){
 const t=getCopy(locale);const [guide,setGuide]=useState<Guide>(()=>getDemoGuide(locale));const [status,setStatus]=useState('');const [ready,setReady]=useState(false);
 useEffect(()=>{let draft=getDemoGuide(locale);try{draft=parseDraft(localStorage.getItem(draftKey(locale)),locale);}catch{/* Defaults remain usable. */}requestAnimationFrame(()=>{setGuide(draft);setReady(true);});},[locale]);
 function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();try{localStorage.setItem(draftKey(locale),JSON.stringify(guide));setStatus(t.saved);}catch{setStatus(locale==='ro'?'Browserul nu permite salvarea locală.':locale==='de'?'Der Browser erlaubt kein lokales Speichern.':'The browser does not allow local saving.');}}
 function updateZone(index:number,field:'title'|'description'|'note'|'next',value:string){setGuide(current=>({...current,zones:current.zones.map((zone,i)=>i===index?{...zone,[field]:value}:zone)}));setStatus('');}
 function updateSensory(index:number,key:keyof SensoryProfile,value:SensoryLevel){setGuide(current=>({...current,zones:current.zones.map((zone,i)=>i===index?{...zone,sensory:{...zone.sensory,[key]:value}}:zone)}));setStatus('');}
 return <form onSubmit={save}><label className="form-field">{t.guideName}<input disabled={!ready} value={guide.title} onChange={e=>setGuide({...guide,title:e.target.value})} required maxLength={160}/></label>{guide.zones.map((zone,index)=><section className="builder-zone" key={zone.id}><h2>{t.step} {index+1} · {zone.title}</h2><div className="form-grid"><label className="form-field wide">{t.zoneName}<input disabled={!ready} value={zone.title} onChange={e=>updateZone(index,'title',e.target.value)} required maxLength={160}/></label><label className="form-field wide">{t.description}<textarea disabled={!ready} value={zone.description} onChange={e=>updateZone(index,'description',e.target.value)} required rows={3} maxLength={2000}/></label></div><fieldset className="sensory-fields"><legend>{locale==='ro'?'Profil senzorial':locale==='de'?'Sensorisches Profil':'Sensory profile'}</legend>{(['sound','light','crowding','smell','temperature','visual'] as (keyof SensoryProfile)[]).map(key=><label className="form-field" key={key}>{t[key]}<select disabled={!ready} value={zone.sensory[key]} onChange={e=>updateSensory(index,key,e.target.value as SensoryLevel)}>{(['unknown','low','moderate','high','variable'] as SensoryLevel[]).map(level=><option key={level} value={level}>{t[level]}</option>)}</select></label>)}</fieldset><label className="form-field">{t.note}<textarea disabled={!ready} value={zone.note} onChange={e=>updateZone(index,'note',e.target.value)} rows={2} maxLength={2000}/></label><label className="form-field">{t.predictability}<textarea disabled={!ready} value={zone.next} onChange={e=>updateZone(index,'next',e.target.value)} rows={2} maxLength={2000}/></label></section>)}<div className="button-row"><button className="button" type="submit" disabled={!ready}><Save size={17} aria-hidden="true"/>{t.save}</button><Link className="button button-outline" href={`/${locale}/dashboard/preview`}>{t.previewGuide}<ArrowUpRight size={17} aria-hidden="true"/></Link></div><p className="status-message" role="status">{status}</p><div className="notice">{t.publishUnavailable}</div></form>;
}
export function ResetDraft({locale}:{locale:Locale}){const t=getCopy(locale);const [status,setStatus]=useState('');function reset(){try{localStorage.setItem(draftKey(locale),JSON.stringify(getDemoGuide(locale)));setStatus(t.draftReset);}catch{setStatus(locale==='ro'?'Browserul nu permite salvarea locală.':locale==='de'?'Lokales Speichern nicht möglich.':'Local storage is unavailable.');}}return <><button className="button button-outline" onClick={reset}>{t.clearDraft}</button><p className="status-message" role="status">{status}</p></>;}
