'use client';
import Image from 'next/image';
import { useState, useRef, useEffect } from 'react';
import { ArrowLeft, ArrowRight, ShieldCheck, CheckCircle2 } from 'lucide-react';
import { getCopy, type Locale } from '@/lib/i18n';
import { getDemoGuide, parseDraft, draftKey, type Guide, type SensoryProfile } from '@/lib/demo';
import { getOrganisationCopy } from '@/lib/organisation-copy';
import { ReadAloud } from './read-aloud';
import { spokenGuide, spokenZone } from '@/lib/speech';
import { GuideText } from './guide-text';
import { getAccessCopy } from '@/lib/accessibility-copy';
import { useLocalPhoto } from './zone-photo';
export function GuideViewer({locale,preview=false}:{locale:Locale;preview?:boolean}) {
  const t=getCopy(locale);const a=getAccessCopy(locale);const [textView,setTextView]=useState(false);const [guide,setGuide]=useState<Guide>(()=>getDemoGuide(locale));const [index,setIndex]=useState(0);const titleRef=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{ if(!preview)return;try{const draft=parseDraft(localStorage.getItem(draftKey(locale)),locale);requestAnimationFrame(()=>setGuide(draft));}catch{/* Default example is still usable. */} },[locale,preview]);
  function move(next:number) {setTextView(false);setIndex(next);requestAnimationFrame(()=>titleRef.current?.focus());}
  function displayText(show:boolean) {setTextView(show);requestAnimationFrame(()=>titleRef.current?.focus());}
  const zone=guide.zones[index];
  const localPhoto=useLocalPhoto(preview?zone?.photo?.id:undefined);
  const info=[[t.arrival,t.arrivalBody],[t.general,t.generalBody],[t.provenance,t.provenanceBody]];
  return <>{preview ? <div><div className="notice">{t.previewNotice}</div><h2 className="local-guide-title">{guide.title}</h2></div> : null}<div className="guide-display"><p className="notice sound-independent">{a.withoutSound}</p><div className="button-row" role="group" aria-label={a.display}><button type="button" className="button button-outline" aria-pressed={!textView} onClick={()=>displayText(false)}>{a.stepByStep}</button><button type="button" className="button button-outline" aria-pressed={textView} onClick={()=>displayText(true)}>{a.fullText}</button></div><ReadAloud key={textView?'full-text':zone?.id||'completion'} locale={locale} label={textView?a.listenGuide:a.listenStep} text={textView?spokenGuide(guide,locale):zone?t.demo+'\n'+t.source+'\n'+spokenZone(zone,locale,index,guide.zones.length):t.completed+'\n'+t.completedBody}/></div><div className={`guide-layout${textView?' is-text-view':''}`}>{!textView && <aside className="guide-sidebar"><h2>{t.guideIndex}</h2><ol>{guide.zones.map((item,i)=><li key={item.id}><button onClick={()=>move(i)} aria-current={index===i?'step':undefined}><span>0{i+1}</span>{item.title}</button></li>)}</ol><p className="source-label"><ShieldCheck size={14} aria-hidden="true"/>{t.source}</p></aside>}<div>
    {textView ? <GuideText locale={locale} guide={guide} headingRef={titleRef}/> : zone ? <article className="guide-card"><div className="guide-progress"><span className="small-label">{t.step} {index+1} {t.of} {guide.zones.length}</span><progress value={index+1} max={guide.zones.length} aria-label={t.guideIndex}/></div><div className="guide-media"><Image data-reading-anchor className="guide-image" unoptimized={Boolean(localPhoto?.url)} src={localPhoto?.url||zone.illustration} alt={localPhoto?.url?zone.photo!.alt:t.illustration+': '+zone.title} width={600} height={400} priority/></div><div className="guide-content">{preview&&zone.photo&&localPhoto&&!localPhoto.url?<p className="notice">{getOrganisationCopy(locale).photoMissing}</p>:null}{preview&&localPhoto?.url&&zone.photo?<p className="small-note">{zone.photo.rights} · {zone.photo.photographedOn}</p>:null}<h2 ref={titleRef} tabIndex={-1}>{zone.title}</h2><p>{zone.description}</p><div className="sensory-grid">{(['sound','light','crowding','smell','temperature','visual'] as (keyof SensoryProfile)[]).map(key=><div className="sensory-item" key={key}><span>{t[key]}</span><strong><i className="level-dot" aria-hidden="true"/>{t[zone.sensory[key]]}</strong></div>)}</div><div className="callout"><h3>{t.support}</h3><p>{zone.note}</p></div><h3>{t.predictability}</h3><p>{zone.next}</p><nav className="guide-navigation" aria-label={t.guideIndex}><button className="button button-outline" disabled={index===0} onClick={()=>move(index-1)}><ArrowLeft size={17} aria-hidden="true"/>{t.previous}</button><button className="button" onClick={()=>move(index+1)}>{index===guide.zones.length-1?t.finish:t.next}<ArrowRight size={17} aria-hidden="true"/></button></nav></div></article>
    : <div className="completion"><CheckCircle2 size={35} aria-hidden="true"/><h2 ref={titleRef} tabIndex={-1}>{t.completed}</h2><p>{t.completedBody}</p><button className="button" onClick={()=>move(0)}>{t.restart}<ArrowRight size={17} aria-hidden="true"/></button></div>}
    <div className="guide-info">{info.map(([heading,body])=>textView ? <section className="guide-info-text" key={heading}><h3>{heading}</h3><p>{body}</p></section> : <details key={heading}><summary>{heading}</summary><p>{body}</p></details>)}</div><p className="small-label">{t.demo} · {t.methodVersion}</p>
  </div></div></>;
}
