import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, ArrowUpRight, Volume2, Sun, Users, Wind, Armchair, Signpost, Check, BookOpen, Fingerprint, ShieldCheck } from 'lucide-react';
import { getCopy, isLocale } from '@/lib/i18n';
import { notFound } from 'next/navigation';
export default async function Home({params}:{params:Promise<{locale:string}>}){
  const {locale}=await params;if(!isLocale(locale))notFound();const t=getCopy(locale);
  const icons=[Volume2,Sun,Users,Wind,Armchair,Signpost]; const principleIcons=[BookOpen,Fingerprint,ShieldCheck];
  return <main id="main-content"><section className="hero container"><div className="hero-copy"><p className="eyebrow"><span className="tiny-sun" aria-hidden="true"/> {t.eyebrow}</p><h1>{t.heroTitle}<br/><em>{t.heroAccent}</em></h1><p className="hero-description">{t.heroDescription}</p><div className="button-row"><Link className="button" href={`/${locale}/example-guide`}>{t.heroCta}<ArrowUpRight size={18} aria-hidden="true"/></Link><Link className="quiet-link" href={`/${locale}/for-organisations`}>{t.heroSecondary}<ArrowRight size={17} aria-hidden="true"/></Link></div><p className="reassurance"><Check size={15} aria-hidden="true"/>{t.reassurance}</p></div>
    <div className="hero-visual"><div className="visual-orbit" aria-hidden="true"/><div className="preview-card"><div className="preview-card-heading"><span className="small-label">{t.sample}</span><span className="mini-dots" aria-hidden="true">•••</span></div><div className="illustration-frame"><Image src="/illustrations/entrance.svg" alt={t.illustration} width={600} height={400} priority/></div><div className="preview-content"><p className="small-label">01 / 05 · {t.museum}</p><h2>{t.cardTitle}</h2><p>{t.cardDescription}</p><div className="sensory-mini"><span><Volume2 size={15} aria-hidden="true"/>{t.sound}<strong>{t.variable}</strong></span><span><Sun size={15} aria-hidden="true"/>{t.light}<strong>{t.moderate}</strong></span></div><p className="source-label"><ShieldCheck size={14} aria-hidden="true"/>{t.source}</p></div></div><div className="demo-stamp">{t.demo}</div></div>
  </section><div className="principles-band"><div className="container principles-grid">{t.principles.map((title,i)=>{const Icon=principleIcons[i];return <div key={title}><Icon size={21} strokeWidth={1.5} aria-hidden="true"/><div><h2>{title}</h2><p>{t.principlesBody[i]}</p></div></div>;})}</div></div>
  <section className="section container approach-section"><div><p className="eyebrow">{t.approach}</p><h2 className="section-title">{t.approachTitle}</h2></div><div><p className="large-copy">{t.approachBody}</p><Link className="quiet-link" href={`/${locale}/methodology`}>{t.nav[2]}<ArrowRight size={18} aria-hidden="true"/></Link></div></section>
  <section className="section details-section"><div className="container"><p className="eyebrow">{t.understand}</p><h2 className="section-title narrow">{t.understandTitle}</h2><div className="channel-grid">{t.channels.map((title,i)=>{const Icon=icons[i];return <article className="channel-card" key={title}><div className="channel-icon"><Icon size={24} strokeWidth={1.5} aria-hidden="true"/></div><h3>{title}</h3><p>{t.channelBody[i]}</p></article>;})}</div></div></section>
  <section className="section container"><p className="eyebrow">{t.stepsLabel}</p><h2 className="section-title">{t.stepsTitle}</h2><div className="steps-grid">{t.steps.map((step,i)=><article key={step}><span className="step-number">0{i+1}</span><h3>{step}</h3><p>{t.stepsBody[i]}</p></article>)}</div></section>
  <div className="container"><section className="org-banner"><div><p className="eyebrow">{t.nav[1]}</p><h2>{t.orgTitle}</h2><p>{t.orgBody}</p><Link className="button" href={`/${locale}/for-organisations`}>{t.orgCta}<ArrowUpRight size={18} aria-hidden="true"/></Link></div><div className="banner-arches" aria-hidden="true"><i/><i/><i/></div></section></div>
  </main>;
}
